# Generated by Django 5.2.5 on 2025-08-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
