# Generated by Django 5.2.5 on 2025-08-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_student_is_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
    ]
